In [2]:
import sys
import os

sys.path.append(os.path.abspath(".."))
from src.preprocess import process_pipeline

df = process_pipeline("../data/processed/cleaned_spam.csv")
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
from src.preprocess import preprocess_text
df['transformed_message']=df['message'].apply(preprocess_text)
df.head()

,label,message,transformed_message
0,ham,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,ham,Ok lar... Joking wif u oni...,ok lar joke wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entri wkli comp win fa cup final tkt st m...
3,ham,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah dont think goe usf live around though

In [4]:
df['label'] = df['label'].map({'ham': 0, 'spam': 1})

In [5]:
df.to_csv('../data/processed/transformed_spam.csv',index=False)